---
title: "R Notebook"
output: html_notebook
---

```{r}
library(oro.nifti)
library(extrantsr)
library(fslr)
kirby_dir <- "/home/arihant/Code/Neurohacking_data/kirby21"
mridir <- file.path(kirby_dir,"visit_1","113")
T1_file <- file.path(mridir,"113-01-MPRAGE.nii.gz")
T1=readNIfTI(T1_file,reorient=FALSE)
orthographic(T1)
```

```{r}

T2_file <- file.path(mridir,"113-01-T2w.nii.gz")
T2w=readNIfTI(T2_file)
flirt_reg_T2_img=flirt(infile = T2_file,reffile = T1_file,dof=6,verbose=FALSE)
orthographic(flirt_reg_T2_img)

```

```{r}
double_ortho(T1,flirt_reg_T2_img)
```

```{r}
reg_t2_img=ants_regwrite(filename=T2_file,template.file = T1,typeofTransform = "Rigid",verbose=FALSE)
orthographic(reg_t2_img)
```

```{r}
flair_file <- file.path(mridir,"113-01-FLAIR.nii.gz")
reg_flair_img=ants_regwrite(filename=flair_file,template.file = T1,typeofTransform = "Rigid",verbose=FALSE)
orthographic(reg_flair_img)
```
```{r}
double_ortho(T1,reg_t2_img)
double_ortho(T1,reg_flair_img)

```
```{r}
library(scales)
ortho2(T1,reg_t2_img,col.y = alpha(hotmetal(),0.25))
```

