---
title: "WEEK2 Introduction to Neurohacking"
output: html_notebook
---
```{r}
path="/home/arihant/Code/Neurohacking_data/BRAINIX/NIfTI"
setwd(path)
```

function for spline transform
```{r}
lin.sp<- function(x,knots,slope){
knots<- c(min(x),knots,max(x))
slopeS<-slope[1]
for(j in 2:length(slope)){
slopeS<-c(slopeS,slope[j]-sum(slopeS))
}
rvals<-numeric(length(x))
for(i in 2:length(knots))
{
rvals<-ifelse(x>=knots[i-1],slopeS[i-1]*(x-knots[i-1])+rvals,rvals)
}
return (rvals)
}
```


```{r}
smooth.T1 <- GaussSmoothArray(T1,voxdim=c(1,1,1),ksize=11,sigma=diag(3,3),mask=NULL,var.norm=FALSE)

orthographic(smooth.T1)

```

```{r}
mridir <- path_to_nifti
sequence <- "FLAIR"
volume.f <- readNIfTI(file.path(mridir,paste0(sequence,'.nii.gz')),reorient = FALSE)
volume.f <- cal_img(volume.f)
image(volume.f,z=12,plot.type='single')

```
```{r}
sequence <- "T1"
volume.t1 <- readNIfTI(file.path(mridir,sequence),reorient = FALSE)
volume.t1 <- cal_img(volume.t1)
image(volume.t1,z=12,plot.type='single')

```


```{r}
sequence <- "T2"
volume.t2 <- readNIfTI(file.path(mridir,sequence),reorient = FALSE)
volume.t2 <- cal_img(volume.t2)
image(volume.t2,z=12,plot.type='single')

```